on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  test:
    timeout-minutes: 5
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: "false"
      - name: Set up Ruby
        uses: ruby/setup-ruby@cf7216d52fba1017929b4d7162fabe2b30af5b49
        with:
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Fmt check
        run: bundle exec rake check:rufo
      - name: Rbs check
        run: bundle exec rake check:rbs
      - name: Steep
        run: bundle exec rake check:steep
      - name: Run tests
        run: bundle exec rake spec
