on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Fmt check
        run: bundle exec rake check:rufo
      - name: Rbs check
        run: bundle exec rake check:rbs
      - name: Steep
        run: bundle exec rake check:steep
      - name: Run tests
        run: bundle exec rake spec
